# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# this gets the value at index 8
arr[8]

8

In [10]:
arr[1:5]

array([1, 2, 3, 4])

In [11]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [12]:
# same as 0:6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [13]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [14]:
arr[0:5] = 100

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# slicing ----------------------------------------------

In [17]:
slice_of_arr = arr[0:6]

In [18]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [20]:
# boradcasting is a way of changing the values of a slice of an array
# broadcasting is different from copying
# broadcasting is not a copy, it is a view of the original array
# it is a pointer or reference to the original array
# this will change the original array
slice_of_arr[:] = 99  

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# coppy vs view ----------------------------------------------

In [23]:
# this is how to specifically copy an array
arr_copy = arr.copy()

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
# this will not change the original array
arr_copy[:] = 100

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [2]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [3]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# Bracket Notation ----------------------------------------------

In [4]:
# double bracket notation
# row, column
arr_2d[0][0]

5

In [8]:
arr_2d[2][1]

40

In [6]:
# single bracket notation
# this is the same as the double bracket notation
arr_2d[0,0]

5

In [7]:
# this will get the entire row
arr_2d[1]

array([20, 25, 30])

In [10]:
# this will slice (keep) everything up to, but not including, row 2
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [12]:
# this will further slice the columns of the first two rows
# this will keep only columns 1 to the end of the columns of the rows from 0 up to row 2
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Conditional Arrays ----------------------------------------------

In [13]:
arr = np.arange(1,11)

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# using a conditional operator on an array will return a boolean array
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [16]:
bool_arr = arr > 5

In [17]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [18]:
# this will return only the values that are true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [19]:
# conditional selection in one step
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [20]:
# this is not a copy, it is a view of the original array
arr[arr < 3]

array([1, 2])

# exercise  ----------------------------------------------

In [21]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])