NumPy Arrays
* matrix = 2D array = list of lists

CAST normal python list into vector aka 1D array

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

CAST a list of lists into a 2D array

In [5]:
# list of lists
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
# cast to matrix aka 2D array
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# this is a built in function to create arrays
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# this will increase step by 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# create an array of zeros
np.zeros(3)

array([0., 0., 0.])

In [11]:
# create martrix of zeros from tuple
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# create array of ones
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
# create matrix of ones from tuple
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# linspace will return evenly spaced numbers over a specified interval
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
# identity matrix
# useful for linear algebra
# 2d square matrix, same number of rows and columns
# 1s on diagonal, 0s everywhere else
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random

In [3]:
# 1D array with uniform distribution from 0 to 1
np.random.rand(5)

array([0.612942  , 0.59360316, 0.73029087, 0.44474484, 0.12003672])

In [4]:
# for 2D array with uniform distribution from 0 to 1
np.random.rand(5,5)

array([[0.3380141 , 0.8440174 , 0.87813743, 0.71438832, 0.51791393],
       [0.7707526 , 0.21125448, 0.35338695, 0.2162512 , 0.33845083],
       [0.99704503, 0.67676071, 0.52307328, 0.71212041, 0.86404757],
       [0.4843274 , 0.63605514, 0.78519983, 0.84320589, 0.07711238],
       [0.67176287, 0.58348885, 0.71637406, 0.51217775, 0.81776913]])

In [5]:
# to get numbers from standard normal distribution aka gaussian distribution
np.random.randn(2)

array([0.54024163, 0.27098676])

In [6]:
# to get 2D array from standard normal distribution
np.random.randn(2,2)

array([[-0.70380796,  0.14043419],
       [ 0.92632935,  0.84146996]])

In [7]:
# random integers from low to high
# low is inclusive, high is exclusive(1,100 will not include 100)
np.random.randint(1,100)

74

In [8]:
# this will return 10 random integers from 1 to 100
np.random.randint(1,100,10)

array([12,  5, 94,  2,  3, 74,  5,  9, 13, 59])

activity

In [10]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 0, 16, 39, 11, 40, 22, 46, 31, 35, 29])

In [13]:
# will get an error if you try to reshape with a different number of elements
# number of elements must be the same
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
# get max value
ranarr.max()

46

In [16]:
# get min value
ranarr.min()

0

In [17]:
# will return the index location of the max value in the array
ranarr.argmax()

6

In [18]:
# will return the index location of the min value in the array
ranarr.argmin()

0

In [19]:
# get the shape of the array
# single number is 1D array ex. (25,)
# 2 numbers is 2D array ex. (5,5)
arr.shape

(25,)

In [20]:
# returns the data type of the array
arr.dtype

dtype('int32')

In [ ]:
from numpy.random import randint    # this is how you import just a function from a library

In [ ]:
# use randint without np. in front of it
randint(2,10)